%MACRO IMPORT;

%LET ST1 = AL;
%LET ST2 = GA;
%LET ST3 = LA;
%LET ST4 = WV;

%DO I = 1 %TO 4;


PROC IMPORT OUT= BACKESJ.&&ST&I.
            DATAFILE= "S:\DA_work_files\DA_Work_Python\Webscraping\Licensure\&&ST&I. Facilities.xlsx"
            DBMS=XLSX REPLACE;
     SHEET= "Sheet1";
     GETNAMES=YES;
run;

%end;

%mend;

%import;


%MACRO contents;

%LET ST1 = AL;
%LET ST2 = GA;
%LET ST3 = LA;
%LET ST4 = WV;

%DO I = 1 %TO 4;

proc contents data = backesj.&&st&i.;
run;
quit;

%end;

%mend;

%contents;


DATA BACKESJ.ALL_BENES;
LENGTH
RECIP_NAME_LAST $35.
RECIP_NAME_FIRST $30. 
RECIP_NAME_MIDDLE_INIT $15.
recip_address_line_1 recip_address_line_2 $60.
recip_city $30.
recip_id $15.
RECIP_ZIP_CD $9.;
SET 
BACKESJ.PTB_MCARE_BENES
BACKESJ.DME_MCARE_BENES
BACKESJ.MCAID_BENES;
RUN;



* FACILITY STUFF ;



RSUBMIT;

DATA AL_FINAL;
LENGTH
recip_address_line_1 recip_address_line_2 $60.
recip_city $30.
RECIP_ZIP_CD $9.
TELEPHONE $10.;
SET BACKESJ.AL;
recip_address_line_1 = Address_Line_1;
recip_address_line_2 = Address_Line_2;
RECIP_CITY = CITY;
RECIP_ZIP_CD = ZIP;
RECIP_STATE = STATE;
TELEPHONE = COMPRESS(PHONE, "-() ");

RUN;

ENDRSUBMIT;
LIBNAME RWORK SLIBREF = WORK SERVER = SASP;

* ZIP CODE PROBLEM. WHEN COUNTING WORDS, SOMETIMES THE CITY WILL HAVE MULTIPLE NAMES ;
* WE WILL USE THE ZIPCODE TO INDICATE THESE TIMES;


RSUBMIT; 
PROC SQL; 
CREATE TABLE CITY_ZIP AS 
SELECT  
PUT(ZIP, Z5.) AS ZIP,
CITY, 
COUNTW(CITY) AS COUNT 
FROM SASHELP.ZIPCODE  
WHERE CALCULATED COUNT > 1
ORDER BY COUNT DESC; 
QUIT; 
ENDRSUBMIT;


* GET FULL ZIP CODE LIST FOR GA ;

RSUBMIT;

DATA GA_PHYSICAL_ZIP;
LENGTH ZIP2 $5.;
SET BACKESJ.GA;
ZIP2 = COMPRESS(PUT(ZIP, BEST12.));
KEEP ZIP2;
RUN;

DATA GA_MAILING_ZIP;
LENGTH RECIP_ZIP_CD_5 $5.;
SET BACKESJ.GA;
IF COUNTW(MAILING, ',') = 2 THEN DO;
RECIP_ZIP_CD = SUBSTR(MAILING, FIND(MAILING, ',')+5,LENGTH(MAILING));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(MAILING, FIND(MAILING, ',')+5,5);
END;
IF COUNTW(MAILING, ',') = 3 THEN DO;
FIRST = SUBSTR(MAILING, 1, FIND(MAILING, ',')-1);
LAST = SUBSTR(MAILING, FIND(MAILING, ',')+2, LENGTH(MAILING));
SECOND = SUBSTR(LAST, 1, FIND(LAST, ',')-2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
END;
IF COUNTW(MAILING, ',') = 4 THEN DO;
FIRST = SCAN(MAILING, 1, ',');
SECOND = SCAN(MAILING, 2, ',');
THIRD = SCAN(MAILING, 3, ',');
LAST = SCAN(MAILING, 4, ',');
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
KEEP RECIP_ZIP_CD_5;
END;
RUN;

PROC SQL;
CREATE TABLE GA_BOTH_ZIP AS
SELECT DISTINCT RECIP_ZIP_CD_5 AS ZIP 
FROM GA_MAILING_ZIP
WHERE RECIP_ZIP_CD_5 ^=''
UNION
SELECT DISTINCT ZIP2 AS ZIP
FROM GA_PHYSICAL_ZIP
WHERE ZIP2 ^='';
QUIT;
ENDRSUBMIT;

RSUBMIT;
PROC SQL;
CREATE TABLE CHECK_ZIP AS
SELECT A.*, B.COUNT FROM 
GA_BOTH_ZIP A LEFT JOIN CITY_ZIP B
ON A.ZIP = B.ZIP
ORDER BY B.COUNT DESC;
QUIT;

ENDRSUBMIT;

RSUBMIT;

PROC SQL NOPRINT;
SELECT DISTINCT STRIP("'"||STRIP(ZIP)||"'") INTO :ZIPS SEPARATED BY ', '
FROM CITY_ZIP WHERE ZIP IN (SELECT DISTINCT ZIP FROM GA_BOTH_ZIP);
QUIT;
ENDRSUBMIT;



RSUBMIT;

DATA GA_PHYSICAL;
LENGTH
recip_address_line_1 recip_address_line_2 $60.
recip_city $30.
RECIP_ZIP_CD $9.
RECIP_ZIP_CD_5 $5.

TELEPHONE TELEPHONE1 TELEPHONE2 $10.;
SET BACKESJ.GA;
recip_address_line_1 = ADDRESS;
RECIP_CITY  = CITY;
RECIP_STATE = STATE;
RECIP_ZIP_CD = COMPRESS(PUT(ZIP, BEST12.));
RECIP_ZIP_CD_5 = SUBSTR(COMPRESS(PUT(ZIP, BEST12.)), 1,5) ;
TELEPHONE = COMPRESS(PUT(PHONE, BEST12.));
TYPE = 'PHYS';
RUN;

ENDRSUBMIT;

RSUBMIT;


* PARSE MAILING;
DATA GA_MAILING;
LENGTH
recip_address_line_1 recip_address_line_2 $60.
recip_city $30.
RECIP_ZIP_CD $9.
RECIP_ZIP_CD_5 $5.
TELEPHONE TELEPHONE1 TELEPHONE2 $10.;
SET BACKESJ.GA;
IF COUNTW(MAILING, ',') = 2 THEN DO;
FIRST = SCAN(MAILING, 1, ',');
LAST = SCAN(MAILING, 2, ',');
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
IF RECIP_ZIP_CD_5 IN (&ZIPS.) THEN DO;
CALL SCAN(FIRST, -2, LAST_POS, LAST_LENGTH);
CALL SCAN(FIRST, -1, LAST_POS2, LAST_LENGTH2);
LAST_WORD = SUBSTR(FIRST, LAST_POS, LAST_LENGTH+LAST_LENGTH2+1);
recip_address_line_1 = TRANWRD(FIRST, STRIP(LAST_WORD), '');

IF ANYLOWER(LAST_WORD) > 0 THEN DO;
CITY_START = ANYUPPER(FIRST,-LENGTH(FIRST));
LAST_WORD = UPCASE(SUBSTR(FIRST, CITY_START, LENGTH(FIRST)-CITY_START+1));
recip_address_line_1 = SUBSTR(FIRST, 1, CITY_START-1);
LOW = ANYLOWER(SUBSTR(FIRST, LAST_POS, LAST_LENGTH),1);
END;

END;
IF RECIP_ZIP_CD_5 NOT IN (&ZIPS.) THEN DO;
CALL SCAN(FIRST, -1, LAST_POS, LAST_LENGTH);
LAST_WORD = SUBSTR(FIRST, LAST_POS, LAST_LENGTH);
recip_address_line_1 = TRANWRD(FIRST, STRIP(LAST_WORD), '');

IF ANYLOWER(LAST_WORD) > 0 THEN DO;
CITY_START = ANYUPPER(FIRST,-LENGTH(FIRST));
LAST_WORD = UPCASE(SUBSTR(FIRST, CITY_START, LENGTH(FIRST)-CITY_START+1));
recip_address_line_1 = SUBSTR(FIRST, 1, CITY_START-1);
LOW = ANYLOWER(SUBSTR(FIRST, LAST_POS, LAST_LENGTH),1);
END;
END;
END;

IF COUNTW(MAILING, ',') = 3 THEN DO;
FIRST = SCAN(MAILING, 1, ',');
SECOND = SCAN(MAILING, 2, ',');
LAST = SCAN(MAILING, 3, ',');
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
IF RECIP_ZIP_CD_5 IN (&ZIPS.) THEN DO;
CALL SCAN(SECOND, -2, LAST_POS, LAST_LENGTH);
CALL SCAN(SECOND, -1, LAST_POS2, LAST_LENGTH2);
LAST_WORD = SUBSTR(SECOND, LAST_POS, LAST_LENGTH+LAST_LENGTH2+1);
recip_address_line_1 = FIRST;
recip_address_line_2 = TRANWRD(SECOND, STRIP(LAST_WORD), '');

IF ANYLOWER(LAST_WORD) > 0 THEN DO;
CITY_START = ANYUPPER(SECOND,-LENGTH(SECOND));
LAST_WORD = UPCASE(SUBSTR(SECOND, CITY_START, LENGTH(SECOND)-CITY_START+1));
recip_address_line_1 = FIRST;
recip_address_line_2 = SUBSTR(SECOND, 1, CITY_START-1);
/*LOW = ANYLOWER(SUBSTR(ADD, LAST_POS, LAST_LENGTH),1);*/
END;


END;
IF RECIP_ZIP_CD_5 NOT IN (&ZIPS.) THEN DO;
CALL SCAN(SECOND, -1, LAST_POS, LAST_LENGTH);
LAST_WORD = SUBSTR(SECOND, LAST_POS, LAST_LENGTH);
recip_address_line_1 = FIRST;
recip_address_line_2 = TRANWRD(SECOND, STRIP(LAST_WORD), '');


IF ANYLOWER(LAST_WORD) > 0 THEN DO;
CITY_START = ANYUPPER(SECOND,-LENGTH(SECOND));
LAST_WORD = UPCASE(SUBSTR(SECOND, CITY_START, LENGTH(SECOND)-CITY_START+1));
recip_address_line_1 = FIRST;
recip_address_line_2 = SUBSTR(SECOND, 1, CITY_START-1);
/*LOW = ANYLOWER(SUBSTR(ADD, LAST_POS, LAST_LENGTH),1);*/
END;
END;

/*CALL SCAN(SECOND, -1, LAST_POS, LAST_LENGTH);*/
/*LAST_WORD = SUBSTR(SECOND, LAST_POS, LAST_LENGTH);*/
/*recip_address_line_1 = FIRST;*/
/*IF LAST_POS > 2 THEN recip_address_line_2 = SUBSTR(SECOND, 1, LAST_POS-2);*/
/*IF LAST_POS < 3 THEN*/
/*recip_address_line_2 = '';*/

END;
IF COUNTW(MAILING, ',') = 4 THEN DO;
FIRST = SCAN(MAILING, 1, ',');
SECOND = SCAN(MAILING, 2, ',');
THIRD = SCAN(MAILING, 3, ',');
LAST = SCAN(MAILING, 4, ',');
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
IF RECIP_ZIP_CD_5 IN (&ZIPS.) THEN DO;
CALL SCAN(THIRD, -2, LAST_POS, LAST_LENGTH);
CALL SCAN(THIRD, -1, LAST_POS2, LAST_LENGTH2);
LAST_WORD = SUBSTR(THIRD, LAST_POS, LAST_LENGTH+LAST_LENGTH2+1);
recip_address_line_1 = CATX(' ', FIRST, SECOND);
recip_address_line_2 = TRANWRD(THIRD, STRIP(LAST_WORD), '');
END;
IF RECIP_ZIP_CD_5 NOT IN (&ZIPS.) THEN DO;
CALL SCAN(THIRD, -1, LAST_POS, LAST_LENGTH);
LAST_WORD = SUBSTR(THIRD, LAST_POS, LAST_LENGTH);
recip_address_line_1 = CATX(' ', FIRST, SECOND);
recip_address_line_2 = TRANWRD(THIRD, STRIP(LAST_WORD), '');
END;
END;
TYPE = 'MAIL';
RECIP_CITY = LAST_WORD;
TELEPHONE = COMPRESS(PUT(PHONE,BEST12.));
KEEP recip_address_line_1 recip_address_line_2 recip_city RECIP_ZIP_CD RECIP_ZIP_CD_5 RECIP_STATE TELEPHONE TYPE
TELEPHONE TELEPHONE1 TELEPHONE2;


RUN;
ENDRSUBMIT;


RSUBMIT;


DATA GA_FINAL;
SET GA_MAILING GA_PHYSICAL;
WHERE recip_address_line_1 ^ ='';
KEEP recip_address_line_1 recip_address_line_2 recip_city RECIP_ZIP_CD RECIP_STATE TELEPHONE TYPE;
RUN;

PROC SQL;
CREATE TABLE GA_FINAL AS
SELECT DISTINCT recip_address_line_1,
recip_address_line_2,
recip_city,
RECIP_ZIP_CD,
RECIP_STATE,
TELEPHONE FROM GA_FINAL;
QUIT;

ENDRSUBMIT;




* LA;


RSUBMIT;

PROC SQL;
CREATE TABLE COUNTS AS SELECT DISTINCT COUNTW(MAILING, ',') AS MAILING, COUNTW(PHYSICAL, ',') AS PHYSICAL
FROM BACKESJ.LA;
QUIT;

ENDRSUBMIT;


* HANDLE SPECIAL ANOMALIES ;

RSUBMIT;


DATA LA_PHYSICAL;
SET BACKESJ.LA;
DROP MAILING;
PHYSICAL = TRANWRD(PHYSICAL, 'A,B,E,F', 'A B E F');
PHYSICAL = TRANWRD(PHYSICAL, 'E,F,G', 'E F G');
TYPE = 'PHYS';
RUN;

DATA LA_MAILING;
SET BACKESJ.LA;
DROP PHYSICAL;
MAILING = TRANWRD(MAILING, '127 W BROAD ST, STE 700, LAKE CHARLES, LA 70601 Lake Charles , LA 70605', '127 W BROAD ST, STE 700 LAKE CHARLES, LA 70601');
MAILING = TRANWRD(MAILING, "2645 O'Neal Lane, Bldg, A, Suite A Baton Rouge, LA 70816", "2645 O'Neal Lane, Bldg A, Suite A Baton Rouge, LA 70816");
TYPE = 'MAIL';
RUN;

ENDRSUBMIT;


* get full zip code list;

RSUBMIT;

DATA LA_MAILING_ZIP;
SET LA_MAILING;
IF COUNTW(MAILING, ',') = 2 THEN DO;
FIRST = SCAN(MAILING, 1, ',');
LAST = SCAN(MAILING, 2, ',');
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
END;
IF COUNTW(MAILING, ',') = 3 THEN DO;
FIRST = SCAN(MAILING, 1, ',');
SECOND = SCAN(MAILING, 2, ',');
LAST = SCAN(MAILING, 3, ',');
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
END;
IF COUNTW(MAILING, ',') = 3 THEN DO;
FIRST = SCAN(MAILING, 1, ',');
SECOND = SCAN(MAILING, 2, ',');
LAST = SCAN(MAILING, 3, ',');
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
END;
KEEP RECIP_ZIP_CD_5;
RUN;

DATA LA_PHYSICAL_ZIP;
SET LA_PHYSICAL;
IF COUNTW(PHYSICAL, ',') = 2 THEN DO;
FIRST = SCAN(PHYSICAL, 1, ',');
LAST = SCAN(PHYSICAL, 2, ',');
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
END;
IF COUNTW(MAILING, ',') = 3 THEN DO;
FIRST = SCAN(PHYSICAL, 1, ',');
SECOND = SCAN(PHYSICAL, 2, ',');
LAST = SCAN(PHYSICAL, 3, ',');
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
END;
IF COUNTW(PHYSICAL, ',') = 3 THEN DO;
FIRST = SCAN(PHYSICAL, 1, ',');
SECOND = SCAN(PHYSICAL, 2, ',');
LAST = SCAN(MAILING, 3, ',');
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
END;
KEEP RECIP_ZIP_CD_5;
RUN;

PROC SQL;
CREATE TABLE LA_BOTH_ZIP AS
SELECT DISTINCT RECIP_ZIP_CD_5 AS ZIP 
FROM LA_MAILING_ZIP
WHERE RECIP_ZIP_CD_5 ^=''
UNION
SELECT DISTINCT RECIP_ZIP_CD_5 AS ZIP
FROM LA_PHYSICAL_ZIP
WHERE RECIP_ZIP_CD_5 ^='';
QUIT;

ENDRSUBMIT;

RSUBMIT;
PROC SQL;
CREATE TABLE CHECK_ZIP AS
SELECT A.*, B.COUNT FROM 
LA_BOTH_ZIP A LEFT JOIN CITY_ZIP B
ON A.ZIP = B.ZIP
ORDER BY B.COUNT DESC;
QUIT;

ENDRSUBMIT;

RSUBMIT;

PROC SQL NOPRINT;
SELECT DISTINCT STRIP("'"||STRIP(ZIP)||"'") INTO :ZIPS SEPARATED BY ', '
FROM CITY_ZIP WHERE ZIP IN (SELECT DISTINCT ZIP FROM LA_BOTH_ZIP);
QUIT;
ENDRSUBMIT;

RSUBMIT;


* PARSE MAILING;
DATA LA_MAILING2;
LENGTH
recip_address_line_1 recip_address_line_2 $60.
recip_city $30.
RECIP_ZIP_CD $9.
RECIP_ZIP_CD_5 $5.
TELEPHONE TELEPHONE1 TELEPHONE2 $10.;
SET LA_MAILING;
IF COUNTW(MAILING, ',') = 2 THEN DO;
FIRST = SCAN(MAILING, 1, ',');
LAST = SCAN(MAILING, 2, ',');
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
IF RECIP_ZIP_CD_5 IN (&ZIPS.) THEN DO;
CALL SCAN(FIRST, -2, LAST_POS, LAST_LENGTH);
CALL SCAN(FIRST, -1, LAST_POS2, LAST_LENGTH2);
LAST_WORD = SUBSTR(FIRST, LAST_POS, LAST_LENGTH+LAST_LENGTH2+1);
recip_address_line_1 = TRANWRD(FIRST, STRIP(LAST_WORD), '');
END;
IF RECIP_ZIP_CD_5 NOT IN (&ZIPS.) THEN DO;
CALL SCAN(FIRST, -1, LAST_POS, LAST_LENGTH);
LAST_WORD = SUBSTR(FIRST, LAST_POS, LAST_LENGTH);
recip_address_line_1 = TRANWRD(FIRST, STRIP(LAST_WORD), '');
END;
END;
IF COUNTW(MAILING, ',') = 3 THEN DO;
FIRST = SCAN(MAILING, 1, ',');
SECOND = SCAN(MAILING, 2, ',');
LAST = SCAN(MAILING, 3, ',');
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
IF RECIP_ZIP_CD_5 IN (&ZIPS.) THEN DO;
CALL SCAN(SECOND, -2, LAST_POS, LAST_LENGTH);
CALL SCAN(SECOND, -1, LAST_POS2, LAST_LENGTH2);
LAST_WORD = SUBSTR(SECOND, LAST_POS, LAST_LENGTH+LAST_LENGTH2+1);
recip_address_line_1 = FIRST;
recip_address_line_2 = TRANWRD(SECOND, STRIP(LAST_WORD), '');
END;
IF RECIP_ZIP_CD_5 NOT IN (&ZIPS.) THEN DO;
CALL SCAN(SECOND, -1, LAST_POS, LAST_LENGTH);
LAST_WORD = SUBSTR(SECOND, LAST_POS, LAST_LENGTH);
recip_address_line_1 = FIRST;
recip_address_line_2 = TRANWRD(SECOND, STRIP(LAST_WORD), '');
END;

/*CALL SCAN(SECOND, -1, LAST_POS, LAST_LENGTH);*/
/*LAST_WORD = SUBSTR(SECOND, LAST_POS, LAST_LENGTH);*/
/*recip_address_line_1 = FIRST;*/
/*IF LAST_POS > 2 THEN recip_address_line_2 = SUBSTR(SECOND, 1, LAST_POS-2);*/
/*IF LAST_POS < 3 THEN*/
/*recip_address_line_2 = '';*/
END;
IF COUNTW(MAILING, ',') = 4 THEN DO;
FIRST = SCAN(MAILING, 1, ',');
SECOND = SCAN(MAILING, 2, ',');
THIRD = SCAN(MAILING, 3, ',');
LAST = SCAN(MAILING, 4, ',');
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
IF RECIP_ZIP_CD_5 IN (&ZIPS.) THEN DO;
CALL SCAN(THIRD, -2, LAST_POS, LAST_LENGTH);
CALL SCAN(THIRD, -1, LAST_POS2, LAST_LENGTH2);
LAST_WORD = SUBSTR(THIRD, LAST_POS, LAST_LENGTH+LAST_LENGTH2+1);
recip_address_line_1 = CATX(' ', FIRST, SECOND);
recip_address_line_2 = TRANWRD(THIRD, STRIP(LAST_WORD), '');
END;
IF RECIP_ZIP_CD_5 NOT IN (&ZIPS.) THEN DO;
CALL SCAN(THIRD, -1, LAST_POS, LAST_LENGTH);
LAST_WORD = SUBSTR(THIRD, LAST_POS, LAST_LENGTH);
recip_address_line_1 = CATX(' ', FIRST, SECOND);
recip_address_line_2 = TRANWRD(THIRD, STRIP(LAST_WORD), '');
END;
END;
TYPE = 'MAIL';
RECIP_CITY = LAST_WORD;
TELEPHONE = COMPRESS(PUT(PHONE0,BEST12.));
TELEPHONE1 = COMPRESS(PUT(PHONE1,BEST12.));
TELEPHONE2 = COMPRESS(PUT(PHONE2,BEST12.));
KEEP recip_address_line_1 recip_address_line_2 recip_city RECIP_ZIP_CD RECIP_ZIP_CD_5 RECIP_STATE TELEPHONE TYPE
TELEPHONE TELEPHONE1 TELEPHONE2;
RUN;
ENDRSUBMIT;

RSUBMIT;


* PARSE PHYSICAL;
DATA LA_PHYSICAL2;
LENGTH
recip_address_line_1 recip_address_line_2 $60.
recip_city $30.
RECIP_ZIP_CD $9.
RECIP_ZIP_CD_5 $5.
TELEPHONE TELEPHONE1 TELEPHONE2 $10.;
SET LA_PHYSICAL;
IF COUNTW(PHYSICAL, ',') = 2 THEN DO;
FIRST = SCAN(PHYSICAL, 1, ',');
LAST = SCAN(PHYSICAL, 2, ',');
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
IF RECIP_ZIP_CD IN (&ZIPS.) THEN DO;
CALL SCAN(FIRST, -2, LAST_POS, LAST_LENGTH);
CALL SCAN(FIRST, -1, LAST_POS2, LAST_LENGTH2);
LAST_WORD = SUBSTR(FIRST, LAST_POS, LAST_LENGTH+LAST_LENGTH2+1);
recip_address_line_1 = TRANWRD(FIRST, STRIP(LAST_WORD), '');
END;
IF RECIP_ZIP_CD NOT IN (&ZIPS.) THEN DO;
CALL SCAN(FIRST, -1, LAST_POS, LAST_LENGTH);
LAST_WORD = SUBSTR(FIRST, LAST_POS, LAST_LENGTH);
recip_address_line_1 = TRANWRD(FIRST, STRIP(LAST_WORD), '');
END;
END;
IF COUNTW(PHYSICAL, ',') = 3 THEN DO;
FIRST = SCAN(PHYSICAL, 1, ',');
SECOND = SCAN(PHYSICAL, 2, ',');
LAST = SCAN(PHYSICAL, 3, ',');
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
IF RECIP_ZIP_CD IN (&ZIPS.) THEN DO;
CALL SCAN(SECOND, -2, LAST_POS, LAST_LENGTH);
CALL SCAN(SECOND, -1, LAST_POS2, LAST_LENGTH2);
LAST_WORD = SUBSTR(SECOND, LAST_POS, LAST_LENGTH+LAST_LENGTH2+1);
recip_address_line_1 = FIRST;
recip_address_line_2 = TRANWRD(SECOND, STRIP(LAST_WORD), '');
END;
IF RECIP_ZIP_CD NOT IN (&ZIPS.) THEN DO;
CALL SCAN(SECOND, -1, LAST_POS, LAST_LENGTH);
LAST_WORD = SUBSTR(SECOND, LAST_POS, LAST_LENGTH);
recip_address_line_1 = FIRST;
recip_address_line_2 = TRANWRD(SECOND, STRIP(LAST_WORD), '');
END;

/*CALL SCAN(SECOND, -1, LAST_POS, LAST_LENGTH);*/
/*LAST_WORD = SUBSTR(SECOND, LAST_POS, LAST_LENGTH);*/
/*recip_address_line_1 = FIRST;*/
/*IF LAST_POS > 2 THEN recip_address_line_2 = SUBSTR(SECOND, 1, LAST_POS-2);*/
/*IF LAST_POS < 3 THEN*/
/*recip_address_line_2 = '';*/
END;
IF COUNTW(PHYSICAL, ',') = 4 THEN DO;
FIRST = SCAN(PHYSICAL, 1, ',');
SECOND = SCAN(PHYSICAL, 2, ',');
THIRD = SCAN(PHYSICAL, 3, ',');
LAST = SCAN(PHYSICAL, 4, ',');
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
IF RECIP_ZIP_CD IN (&ZIPS.) THEN DO;
CALL SCAN(THIRD, -2, LAST_POS, LAST_LENGTH);
CALL SCAN(THIRD, -1, LAST_POS2, LAST_LENGTH2);
LAST_WORD = SUBSTR(THIRD, LAST_POS, LAST_LENGTH+LAST_LENGTH2+1);
recip_address_line_1 = CATX(' ', FIRST, SECOND);
recip_address_line_2 = TRANWRD(THIRD, STRIP(LAST_WORD), '');
END;
IF RECIP_ZIP_CD NOT IN (&ZIPS.) THEN DO;
CALL SCAN(THIRD, -1, LAST_POS, LAST_LENGTH);
LAST_WORD = SUBSTR(THIRD, LAST_POS, LAST_LENGTH);
recip_address_line_1 = CATX(' ', FIRST, SECOND);
recip_address_line_2 = TRANWRD(THIRD, STRIP(LAST_WORD), '');
END;
END;
TYPE = 'PYHS';
RECIP_CITY = LAST_WORD;
TELEPHONE = COMPRESS(PUT(PHONE0,BEST12.));
TELEPHONE1 = COMPRESS(PUT(PHONE1,BEST12.));
TELEPHONE2 = COMPRESS(PUT(PHONE2,BEST12.));
KEEP recip_address_line_1 recip_address_line_2 recip_city RECIP_ZIP_CD RECIP_STATE TELEPHONE TYPE
TELEPHONE TELEPHONE1 TELEPHONE2;
RUN;
ENDRSUBMIT;


/*RSUBMIT;*/
/**/
/*%PUT &ZIPS.;*/
/*ENDRSUBMIT;*/
/**/
/*RSUBMIT;*/
/**/
/*PROC SQL;*/
/*SELECT * FROM CITY_ZIP*/
/*WHERE ZIP IN (&ZIPS.);*/
/*QUIT;*/
/*ENDRSUBMIT;*/

RSUBMIT;

DATA LA_FINAL;
LENGTH
recip_address_line_1 recip_address_line_2 $60.
recip_city $30.
RECIP_ZIP_CD $9.
RECIP_ZIP_CD_5 $5.
TELEPHONE TELEPHONE1 TELEPHONE2 $10.;
SET LA_MAILING2
LA_PHYSICAL2;
WHERE recip_address_line_1 ^ ='';
RUN;


PROC SQL;
CREATE TABLE LA_FINAL AS
SELECT DISTINCT recip_address_line_1, recip_address_line_2, recip_city,
RECIP_ZIP_CD, RECIP_STATE, TELEPHONE, TELEPHONE1, TELEPHONE2 FROM LA_FINAL;
QUIT;

ENDRSUBMIT;

* WV;






PROC SQL;
CREATE TABLE LA_MAILING3 AS
SELECT * FROM LA_MAILING2 A, CITY
;


RSUBMIT;

DATA backesj.ALL;
SET GA_FINAL AL_FINAL LA_FINAL;
KEEP  recip_address_line_1 recip_address_line_2 recip_city
RECIP_ZIP_CD TELEPHONE TELEPHONE1 TELEPHONE2;
IF 
TELEPHONE ^='' OR
TELEPHONE1 ^='' OR
TELEPHONE2 ^='';

IF FINDW( UPCASE(recip_address_line_1) , STRIP(UPCASE(RECIP_CITY)) ) > 0 AND
FINDW( UPCASE(recip_address_line_1) , STRIP(UPCASE(RECIP_STATE)) ) > 0 THEN recip_address_line_1 = '';
IF FINDW( UPCASE(recip_address_line_2) , STRIP(UPCASE(RECIP_CITY)) ) > 0 AND
FINDW( UPCASE(recip_address_line_2) , STRIP(UPCASE(RECIP_STATE)) ) > 0 THEN recip_address_line_2 = '';


/*new = FIND(UPCASE(COMPRESS(recip_address_line_1," #")), 'POBOX');*/
/*IF FINDW( UPCASE(COMPRESS('PO BOX'," ")) , 'POBOX') > 0 THEN FLAG4=1;*/
	IF 
	FIND( UPCASE(COMPRESS(recip_address_line_1,"., #")) , 'POBOX') > 0 OR 
	FIND( UPCASE(recip_address_line_1) , 'PMB') > 0 OR
	FIND( UPCASE(COMPRESS(recip_address_line_1,"., ")) , 'OFFICEBOX') > 0 OR 
	FIND( UPCASE(COMPRESS(recip_address_line_1,"., ")) , 'POSTOFFICE') > 0 OR 
	FIND( UPCASE(COMPRESS(recip_address_line_1,"., ")) , 'POSTBOX') > 0 OR 
	FIND( UPCASE(COMPRESS(recip_address_line_1,"., ")) , 'BX') > 0 OR 
	FIND( UPCASE(COMPRESS(recip_address_line_1,"., ")) , 'BOX') > 0 OR 
	FIND( UPCASE(COMPRESS(recip_address_line_1,"., ")) , 'C/O') > 0 OR 
	FIND( UPCASE(recip_address_line_1) , 'LOT ') > 0 OR
	recip_address_line_1 = '' or
	FIND( UPCASE(recip_address_line_1) , 'UNIT ') > 0 OR
	FIND( UPCASE(recip_address_line_1) , 'SUITE') > 0 OR
	FIND( UPCASE(recip_address_line_1) , 'STE ') > 0 OR
	FIND( UPCASE(recip_address_line_1) , 'BUILDING') > 0 OR
	FIND( UPCASE(recip_address_line_1) , 'BLDG') > 0 OR
	( FIND( UPCASE(recip_address_line_1) , 'APT') > 0 AND LENGTH(recip_address_line_1) le LENGTH(recip_address_line_2)+3 ) or
	( FIND( UPCASE(recip_address_line_1) , 'RM') > 0 AND LENGTH(recip_address_line_1) le LENGTH(recip_address_line_2)+3 ) or
	( FIND( UPCASE(recip_address_line_1) , 'ROOM') > 0 AND LENGTH(recip_address_line_1) le LENGTH(recip_address_line_2)+3 )
	THEN DO;
	FLAG = 1;
	TEMP = recip_address_line_1;
	recip_address_line_1 = recip_address_line_2;
	recip_address_line_2 = TEMP;
END;

RUN;

ENDRSUBMIT;






















proc export data=rwork.cover
outfile="&filepath"
dbms =xlsx replace label;
sheet="Info";
run;





ADD = SUBSTR(MAILING, 1, FIND(MAILING, ',')-2);
RECIP_STATE = SUBSTR(MAILING, FIND(MAILING, ',')+2,2);

RECIP_ZIP_CD = SUBSTR(MAILING, FIND(MAILING, ',')+5,LENGTH(MAILING));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(MAILING, FIND(MAILING, ',')+5,5);
CALL SCAN(ADD, -1, LAST_POS, LAST_LENGTH);
LAST_WORD = SUBSTR(ADD, LAST_POS, LAST_LENGTH);
recip_address_line_1 = SUBSTR(ADD, 1, LAST_POS-2);
END;
IF COUNTW(MAILING, ',') = 3 THEN DO;
FIRST = SUBSTR(MAILING, 1, FIND(MAILING, ',')-1);
LAST = SUBSTR(MAILING, FIND(MAILING, ',')+2, LENGTH(MAILING));
SECOND = SUBSTR(LAST, 1, FIND(LAST, ',')-2);
RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
CALL SCAN(SECOND, -1, LAST_POS, LAST_LENGTH);
LAST_WORD = SUBSTR(SECOND, LAST_POS, LAST_LENGTH);
recip_address_line_1 = FIRST;
IF LAST_POS > 2 THEN recip_address_line_2 = SUBSTR(SECOND, 1, LAST_POS-2);
IF LAST_POS < 3 THEN
recip_address_line_2 = '';
END;

IF COUNTW(MAILING, ',') = 4 THEN DO;
FIRST = SCAN(MAILING, 1, ',');
SECOND = SCAN(MAILING, 2, ',');
THIRD = SCAN(MAILING, 3, ',');
LAST = SCAN(MAILING, 4, ',');

RECIP_STATE = SUBSTR(LAST, FIND(LAST, ',')+2,2);
RECIP_ZIP_CD = SUBSTR(LAST, FIND(LAST, ',')+5,LENGTH(LAST));
IF LENGTH(RECIP_ZIP_CD) = 6 THEN 
RECIP_ZIP_CD = SUBSTR(RECIP_ZIP_CD,1,5);
RECIP_ZIP_CD_5 = SUBSTR(LAST, FIND(LAST, ',')+5,5);
CALL SCAN(THIRD, -1, LAST_POS, LAST_LENGTH);
LAST_WORD = SUBSTR(THIRD, LAST_POS, LAST_LENGTH);
recip_address_line_1 = FIRST;
recip_address_line_2 = SUBSTR(SECOND, 1, LAST_POS-2);
END;

TELEPHONE = PHONE;
RECIP_CITY = LAST_WORD;
TYPE = 'MAIL';
KEEP recip_address_line_1 recip_address_line_2 recip_city RECIP_ZIP_CD RECIP_STATE TELEPHONE TYPE;

RUN;
